version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    volumes:
      - ./init.sql:/dogcker-entrypoint-initdb.d/init.sql