version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: 'java-postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=btest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql